###

POST http://localhost:3000/members/signIn
content-type: application/json

{
// "fullName":"ibad",
"email":"ibad23ahmad@gmail.com",
"password":"22222222"
// "phoneNumber":"921111111111",
// "type":"Gold"
}

###
GET http://localhost:3000/courses/popular
content-type: application/json


